### PR TITLE
Minor grammar corrections and clarifications

### PR DESCRIPTION
**Pull request by sumbach**

### CODE REVIEW

**Comment by denysdovhan** [comment]
Resolve conflict.

**Comment by sumbach** [comment]
Merged conflict resolved.

**Comment by denysdovhan** [comment]
Nope, it didn't.

image

**Comment by sumbach** [comment]
> Nope, it didn't.

It did... until #52 was merged, introducing a new merge conflict.

And now it's fixed again.

**Comment by sumbach** [comment]
Cheers!

**Pull request merged**
