### PR TITLE
Add tip about learnyoubash.

### PR DESCRIPTION
**Pull request by denysdovhan**
As you may noticed, I've made an workshopper based on this book. I think it would be cool when readers can have a practice while they are reading this book.

What do you think @sumbach, @bucaran?

### CODE REVIEW

**Comment by denysdovhan** [comment]
Nobody wants to talk :cry:

**Comment by denysdovhan** [comment]
Nobody wants to discuss :cry:

**Comment by sumbach** [comment]
@denysdovhan Haven't had a chance to check it out yet :anguished: I like the idea--`workshopper` is new to me, but it's an interesting format.

And it looks like it might support translations! (potential answer to #47)

**Comment by denysdovhan** [comment]
Thank you!

**Pull request merged**
