### PR TITLE
Fix some spelling errors and while loop description

### PR DESCRIPTION
**Pull request by Gosha**

### CODE REVIEW

**Comment by denysdovhan** [comment]
Thank you so much!

Will merge as soon as it possible. Now we have merge conflict with #6.

**Comment by denysdovhan** [comment]
@Gosha please, can you reset your https://github.com/Gosha/bash-handbook/commit/3636c9f67c99c1e4ca440dc816dec302f676def4 and do `git push -f`?

If you can, it won't conflict with #6. I ask you to do this, because #6 has better fixes for `while` chapter, so I'm gonna use it.

**Comment by Gosha** [comment]
Done!

**Comment by denysdovhan** [comment]
merged!

**Comment by denysdovhan** [comment]
Published as `1.1.1`.

**Pull request merged**
