### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by andrepolischuk**

### CODE REVIEW

**Comment by denysdovhan** [comment]
I'm realy very grateful for your help, but could you send all your fixes in one pull request? If you can, I'll be grateful in twice!

**Comment by andrepolischuk** [comment]
Ok, I understood.

**Comment by andrepolischuk** [comment]
Thank you for this handbook

**Comment by denysdovhan** [comment]
Thank you for reading!
13 січ. 2016 17:00 "Andrey Polischuk" <notifications@github.com> пише:

**Pull request merged**
