### PR TITLE
Fix rendering issue with ticks not showing up

### PR DESCRIPTION
**Pull request by alebelcor**
I fixed an issue where some ticks were not showing up on rendering. In the process I changed the wording a little bit but I may have misunderstood what you were trying to say.

Please review and let me know. Thank you!

### CODE REVIEW

**Comment by bucaran** [comment]
LGTM @denysdovhan

**Comment by denysdovhan** [comment]
Yep, but it's still broken.

image

At the same time, #2 rendered as it should be rendered. But you have removed `in` — that's a really mitake. Can you remove space between backquotes in the middle — it should fix the rendering? After that, I'm gonna merge it.

**Comment by alebelcor** [comment]
That is very interesting, I thought you necessarily needed to put a space in between, as I did, to get the rendering we wanted. However #2 managed to pull it off without having to add that space, or so I thought.

It's quite clever actually, it looks like @andrepolischuk added "no width space" character between the middle backticks and it's making the rendering look like there's no space in there. Which is the look we want.

**Comment by denysdovhan** [comment]
Now it works:

image

**Comment by denysdovhan** [comment]
Published as `1.2.1`.

**Pull request merged**
