### PR TITLE
Add Chinese translation.

### PR DESCRIPTION
**Pull request by liushuaikobe**
Translation for #65.

### CODE REVIEW

**Comment by denysdovhan** [comment]
I think this is stable enough, 'cause it was reviewed in your repo. Am I right?

Please, add a link to the main `README.md` file.

**Comment by liushuaikobe** [comment]
@denysdovhan Right.  The link is added.

**Comment by denysdovhan** [comment]
Published as `v2.6.0 `! Hooray!

**Comment by liushuaikobe** [comment]
@denysdovhan Great!

**Pull request merged**
