### PR TITLE
Grammar and composition adjustments up to `Arrays` section.

### PR DESCRIPTION
**Pull request by bucaran**
I was able to make corrections and improve the readibility and composition, plus adding a few bits of my own here and there up to the `Arrays` section. This is a living document, so feel free to merge and I will continue from that section and add more corrections again later when I have more time :smile: 

Let me know if there is anything strange or if you have any questions too.

### CODE REVIEW

**Comment by denysdovhan** [comment]
Sorry, but I can't seen your adjustments in **Arrays** section.

**Comment by bucaran** [comment]
Correct. Only _up to_ the **Arrays** section. So, everything _before_ that.

**Comment by denysdovhan** [comment]
Got it. So am I gonna merge

**Comment by bucaran** [comment]
Thanks!

**Comment by denysdovhan** [comment]
Nonono. It's my mistake. I accidentally closed it.
So should I merge it, or maybe better to wait until you finish it?

**Comment by bucaran** [comment]
It's up to you, but I would prefer merging this now so that you can continue adding / editing before I can submit new changes :smile:

**Comment by denysdovhan** [comment]
OK, thank

**Comment by denysdovhan** [comment]
Shit, I hate my phone

**Comment by bucaran** [comment]
:+1:

**Comment by denysdovhan** [comment]
I hope I'll see your future requests :smirk:

**Comment by bucaran** [comment]
I'll send another this week :smile:

**Comment by denysdovhan** [comment]
I hope. Will be grateful.
13 січ. 2016 13:11 "Jorge Bucaran" <notifications@github.com> пише:

**Comment by bucaran** [comment]
No problem! Count on it.

**Pull request merged**
