### PR TITLE
Mschultz4 patch 2

### PR DESCRIPTION
**Pull request by mschultz4**
Fixed several broken links in table of contents

### CODE REVIEW

**Comment by denysdovhan** [comment]
LGTM except _Positional parameters_.

**Comment by mschultz4** [comment]
I changed the section header and contents from argument to parameter, but the entire section uses the term argument.  Should I change all argument references to parameter?

**Comment by denysdovhan** [comment]
Yes, please.

**Comment by sumbach** [comment]
Confirmed that this PR fixes all broken links in the Table of Contents.

**Comment by mschultz4** [comment]
All set.  Please review.

**Pull request merged**
